# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-08 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_content_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featurecontentpage',
            old_name='publication_date',
            new_name='date',
        ),
    ]
