# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-12 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_content_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featurecontentpage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='featurecontentpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='featurecontentpage',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='featurecontentpage',
            name='listing_introduction',
        ),
        migrations.RemoveField(
            model_name='featurecontentpage',
            name='publication_date',
        ),
    ]
