# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-12 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0012_copy_image_permissions_to_collections'),
        ('feature_content_page', '0002_auto_20160512_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurecontentpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', template='blocks/paragraph.html')), ('h1', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='fa-header', template='blocks/h1.html')), ('h2', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='fa-header', template='blocks/h2.html')), ('h3', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='fa-header', template='blocks/h3.html')), ('h4', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='fa-header', template='blocks/h4.html')), ('image', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.CharBlock(blank=True, required=False)), ('style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('', 'Select an image size'), ('full', 'Full-width'), ('half', 'Half-width')], required=False))), icon='image', template='blocks/image.html')), ('blockquote', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.TextBlock()), ('attribute_name', wagtail.wagtailcore.blocks.CharBlock(blank=True, label='e.g. Guy Picciotto', required=False)), ('attribute_group', wagtail.wagtailcore.blocks.CharBlock(blank=True, label='e.g. Fugazi', required=False))), icon='openquote', template='blocks/blockquote.html'))), blank=True),
        ),
        migrations.AddField(
            model_name='featurecontentpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='featurecontentpage',
            name='introduction',
            field=models.TextField(blank=True, help_text='Text to show at the top of the individual page'),
        ),
        migrations.AddField(
            model_name='featurecontentpage',
            name='listing_introduction',
            field=models.CharField(blank=True, help_text="Text shown on listing pages, if empty will show 'Introduction' field content", max_length=250),
        ),
        migrations.AddField(
            model_name='featurecontentpage',
            name='publication_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Post date'),
            preserve_default=False,
        ),
    ]
