# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-12 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feature_content_page', '0003_auto_20160512_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='This is the artist title', max_length=255, null=True, verbose_name='Artist title')),
            ],
            options={
                'verbose_name': 'artist category',
                'verbose_name_plural': 'artist categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ArtistCategoryRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='feature_content_page.ArtistCategory')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_category_relationship', to='feature_content_page.FeatureContentPage')),
            ],
        ),
    ]
