# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-15 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feature_content_page', '0004_auto_20160915_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistfeaturepagerelationship',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_feature_page_relationship', to='artist.Artist'),
        ),
        migrations.AlterField(
            model_name='artistfeaturepagerelationship',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_page_artist_relationship', to='feature_content_page.FeatureContentPage'),
        ),
        migrations.AlterField(
            model_name='authorfeaturepagerelationship',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_page_author_relationship', to='feature_content_page.FeatureContentPage'),
        ),
    ]
