# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-12 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
        ('feature_content_page', '0004_artistcategory_artistcategoryrelationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistFeaturePageRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='artist.Artist')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_feature_page_relationship', to='feature_content_page.FeatureContentPage')),
            ],
        ),
        migrations.DeleteModel(
            name='ArtistCategory',
        ),
        migrations.RemoveField(
            model_name='artistcategoryrelationship',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='artistcategoryrelationship',
            name='page',
        ),
        migrations.DeleteModel(
            name='ArtistCategoryRelationship',
        ),
    ]
