# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-03 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_content_page', '0007_genrefeaturepagerelationship_subgenrefeaturepagerelationship'),
        ('feature_content_page', '0008_auto_20160929_2133'),
    ]

    operations = [
    ]
