# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-12 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_content_page', '0013_auto_20161211_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurecontentpage',
            name='image_choices',
            field=models.CharField(choices=[('fit', 'Contained width'), ('expand', 'Expanded width'), ('full', 'Full width')], default='', max_length=255),
            preserve_default=False,
        ),
    ]
