# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-19 10:11
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtailblocks_cards.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_menus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menumenuitemrelationship',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='menumenuitemrelationship',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='menumenuitemrelationship',
            name='links_in_menu',
        ),
        migrations.AlterModelOptions(
            name='menus',
            options={'verbose_name': 'Navigation menu'},
        ),
        migrations.AlterField(
            model_name='menus',
            name='menu',
            field=wagtail.wagtailcore.fields.StreamField((('menu_item', wagtail.wagtailcore.blocks.StructBlock((('parent_link_text', wagtail.wagtailcore.blocks.CharBlock()), ('parent_internal_link', wagtail.wagtailcore.blocks.PageChooserBlock(blank=True, icon='fa-link', required=False)), ('parent_external_link', wagtail.wagtailcore.blocks.URLBlock(blank=True, icon='fa-link', required=False)), ('child_link', wagtailblocks_cards.blocks.CardsBlock(wagtail.wagtailcore.blocks.StructBlock((('link', wagtail.wagtailcore.blocks.StructBlock((('link_text', wagtail.wagtailcore.blocks.CharBlock()), ('internal_link', wagtail.wagtailcore.blocks.PageChooserBlock(blank=True, icon='fa-link', required=False)), ('external_link', wagtail.wagtailcore.blocks.URLBlock(blank=True, icon='fa-link', required=False))), icon='link')),))))), icon='fa-link')),), blank=True, verbose_name='Menus'),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuMenuItemRelationship',
        ),
    ]
