# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-19 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtailblocks_cards.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160919_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Menu title')),
                ('menu', wagtail.wagtailcore.fields.StreamField((('menu_item', wagtail.wagtailcore.blocks.StructBlock((('parent_link_text', wagtail.wagtailcore.blocks.CharBlock()), ('parent_internal_link', wagtail.wagtailcore.blocks.PageChooserBlock(blank=True, icon='fa-link', required=False)), ('parent_external_link', wagtail.wagtailcore.blocks.URLBlock(blank=True, icon='fa-link', required=False)), ('child_link', wagtailblocks_cards.blocks.CardsBlock(wagtail.wagtailcore.blocks.StructBlock((('link', wagtail.wagtailcore.blocks.StructBlock((('link_text', wagtail.wagtailcore.blocks.CharBlock()), ('internal_link', wagtail.wagtailcore.blocks.PageChooserBlock(blank=True, icon='fa-link', required=False)), ('external_link', wagtail.wagtailcore.blocks.URLBlock(blank=True, icon='fa-link', required=False))), icon='link')),))))), icon='fa-link')),), blank=True, verbose_name='Menus')),
            ],
            options={
                'verbose_name': 'Main navigation menu',
            },
        ),
        migrations.RenameModel(
            old_name='Menu',
            new_name='FooterMenu',
        ),
        migrations.AlterModelOptions(
            name='footermenu',
            options={'verbose_name': 'Footer menu'},
        ),
    ]
