# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 09:36
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtailblocks_cards.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160919_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainmenu',
            options={'verbose_name': 'Main navigation', 'verbose_name_plural': 'Main navigation'},
        ),
        migrations.AlterField(
            model_name='footermenu',
            name='menu',
            field=wagtail.wagtailcore.fields.StreamField((('menu_item', wagtail.wagtailcore.blocks.StructBlock((('parent_link_text', wagtail.wagtailcore.blocks.CharBlock()), ('parent_internal_link', wagtail.wagtailcore.blocks.PageChooserBlock(blank=True, icon='fa-link', required=False)), ('parent_external_link', wagtail.wagtailcore.blocks.CharBlock(blank=True, icon='fa-link', required=False)), ('child_link', wagtailblocks_cards.blocks.CardsBlock(wagtail.wagtailcore.blocks.StructBlock((('link_text', wagtail.wagtailcore.blocks.CharBlock()), ('internal_link', wagtail.wagtailcore.blocks.PageChooserBlock(blank=True, icon='fa-link', required=False)), ('external_link', wagtail.wagtailcore.blocks.CharBlock(blank=True, icon='fa-link', required=False))))))), icon='fa-link')),), blank=True, verbose_name='Menus'),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='menu',
            field=wagtail.wagtailcore.fields.StreamField((('menu_item', wagtail.wagtailcore.blocks.StructBlock((('parent_link_text', wagtail.wagtailcore.blocks.CharBlock()), ('parent_internal_link', wagtail.wagtailcore.blocks.PageChooserBlock(blank=True, icon='fa-link', required=False)), ('parent_external_link', wagtail.wagtailcore.blocks.CharBlock(blank=True, icon='fa-link', required=False)), ('child_link', wagtailblocks_cards.blocks.CardsBlock(wagtail.wagtailcore.blocks.StructBlock((('link_text', wagtail.wagtailcore.blocks.CharBlock()), ('internal_link', wagtail.wagtailcore.blocks.PageChooserBlock(blank=True, icon='fa-link', required=False)), ('external_link', wagtail.wagtailcore.blocks.CharBlock(blank=True, icon='fa-link', required=False))))))), icon='fa-link')),), blank=True, verbose_name='Menus'),
        ),
    ]
