# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-24 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160920_1036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterMenu',
        ),
    ]
