# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-02 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_genreclassalbumrelationship_subgenreclassalbumrelationship'),
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistAlbumRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlbumRelationship', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_album_relationship', to='artist.Artist')),
                ('album', models.ForeignKey(help_text='The album being artisted', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='album.Album')),
            ],
        ),
        migrations.RemoveField(
            model_name='subgenreclassrelationship',
            name='page',
        ),
        migrations.RemoveField(
            model_name='subgenreclassrelationship',
            name='subgenre',
        ),
        migrations.DeleteModel(
            name='SubGenreClassRelationship',
        ),
    ]
