# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_artist_date_formed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='image',
        ),
    ]
