# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-06 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_artist_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', help_text='The name of the page as it will appear in URLs e.g http://domain.com/blog/[my-slug]/', max_length=255),
            preserve_default=False,
        ),
    ]
