# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0008_auto_20160917_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='title',
            field=models.CharField(max_length=254, verbose_name="The artist's name"),
        ),
    ]
