# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-23 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0008_genreclass_image'),
        ('artist', '0009_auto_20160920_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreArtistRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_artist_relationship', to='genre.GenreClass')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_genre_relationship', to='artist.Artist')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
