# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-23 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0010_genreartistrelationship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genreartistrelationship',
            old_name='genre',
            new_name='genres',
        ),
    ]
