# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-25 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20160625_2101'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAlbumRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlbumRelationship', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_album_relationship', to='review.ReviewPage')),
                ('album_name', models.ForeignKey(help_text='The album being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='album.Album')),
            ],
        ),
    ]
