# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-25 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
        ('review', '0002_reviewalbumrelationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewArtistRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArtistRelationship', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_artist_relationship', to='review.ReviewPage')),
                ('artist_name', models.ForeignKey(help_text='The artist who made the album being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='artist.Artist')),
            ],
        ),
    ]
