# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-27 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('review', '0003_reviewpage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAuthorRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorRelationship', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_author_relationship', to='review.ReviewPage')),
                ('author_name', models.ForeignKey(help_text='The author who wrote this', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='author.Author')),
            ],
        ),
    ]
