# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-28 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_auto_20160628_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewalbumrelationship',
            old_name='album_name',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='reviewartistrelationship',
            old_name='artist_name',
            new_name='artist',
        ),
    ]
