# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-12 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_reviewrelatedpagerelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewpage',
            name='date_release',
            field=models.DateField(default='2016-09-12', verbose_name='Release date of album'),
            preserve_default=False,
        ),
    ]
