# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-15 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0012_auto_20160915_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewauthorrelationship',
            old_name='authorRelationship',
            new_name='page',
        ),
        migrations.AlterField(
            model_name='reviewauthorrelationship',
            name='author',
            field=models.ForeignKey(help_text='The author who wrote this', on_delete=django.db.models.deletion.CASCADE, related_name='author_review_relationship', to='author.Author'),
        ),
    ]
