# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-17 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_album_song_details'),
        ('review', '0013_auto_20160916_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewartistrelationship',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='reviewartistrelationship',
            name='page',
        ),
        migrations.RemoveField(
            model_name='reviewexperiment',
            name='AlbumRelationship',
        ),
        migrations.RemoveField(
            model_name='reviewexperiment',
            name='album_ptr',
        ),
        migrations.RenameField(
            model_name='reviewalbumrelationship',
            old_name='AlbumRelationship',
            new_name='pages',
        ),
        migrations.AlterField(
            model_name='reviewalbumrelationship',
            name='album',
            field=models.ForeignKey(help_text='The album being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='album_review_relationship', to='album.Album'),
        ),
        migrations.AlterField(
            model_name='reviewpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow', template='blocks/paragraph.html')), ('h1', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='fa-header', template='blocks/h1.html')), ('h2', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='fa-header', template='blocks/h2.html')), ('h3', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='fa-header', template='blocks/h3.html')), ('h4', wagtail.wagtailcore.blocks.CharBlock(classname='title', icon='fa-header', template='blocks/h4.html')), ('image', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.CharBlock(blank=True, required=False)), ('style', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('', 'Select an image size'), ('full', 'Full-width'), ('half', 'Half-width')], required=False))), icon='image', template='blocks/image.html')), ('blockquote', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.TextBlock()), ('attribute_name', wagtail.wagtailcore.blocks.CharBlock(blank=True, label='e.g. Guy Picciotto', required=False)), ('attribute_group', wagtail.wagtailcore.blocks.CharBlock(blank=True, label='e.g. Fugazi', required=False))), icon='openquote', template='blocks/blockquote.html'))), blank=True, verbose_name='Review body'),
        ),
        migrations.DeleteModel(
            name='ReviewArtistRelationship',
        ),
        migrations.DeleteModel(
            name='ReviewExperiment',
        ),
    ]
