# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-17 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0014_auto_20160917_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewpage',
            name='song_details',
        ),
    ]
