# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-22 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0017_auto_20160920_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewalbumrelationship',
            old_name='pages',
            new_name='page',
        ),
    ]
