# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-03 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0020_auto_20160929_2126'),
        ('review', '0020_auto_20160928_1738'),
    ]

    operations = [
    ]
