# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-21 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('review', '0021_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewFeatureIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Reviews for albums with 4+ reviews',
            },
            bases=('wagtailcore.page',),
        ),
    ]
