# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-23 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('review', '0022_reviewfeatureindexpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewfeatureindexpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='ReviewFeatureIndexPage',
        ),
    ]
