# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-05 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0023_auto_20161023_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewauthorrelationship',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='reviewauthorrelationship',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
