# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-25 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(blank=True, max_length=254, verbose_name="The album's name")),
                ('release_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'ordering': ['album_name'],
            },
        ),
        migrations.CreateModel(
            name='AlbumArtistRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('ArtistRelationship', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_artist_relationship', to='album.Album')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='AlbumSongsRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('album_song', models.CharField(blank=True, max_length=255, verbose_name='Song name')),
                ('album_song_length', models.TimeField(blank=True, verbose_name='Song length')),
                ('album_songs', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_songs_relationship', to='album.Album')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
    ]
