# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-26 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album', '0001_initial'),
        ('artist', '0001_initial'),
        ('wagtailimages', '0013_make_rendition_upload_callable'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumartistrelationship',
            name='artist_name',
            field=models.ForeignKey(help_text='The artist(s) who made this album', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='artist.Artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Album cover image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
