# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-02 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0004_auto_20160626_2011'),
        ('album', '0003_albumindexpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreClassAlbumRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='genre.GenreClass')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_album_relationship', to='album.Album')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubGenreClassAlbumRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgenre_album_relationship', to='album.Album')),
                ('subgenre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='genre.SubgenreClass')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
