# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-17 10:38
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_genreclassalbumrelationship_subgenreclassalbumrelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='song_details',
            field=wagtail.wagtailcore.fields.StreamField((('SongBlock', wagtail.wagtailcore.blocks.StructBlock((('album_song', wagtail.wagtailcore.blocks.CharBlock(blank=True, label='e.g. Waiting Room', required=False)), ('album_song_length', wagtail.wagtailcore.blocks.TimeBlock(blank=True, required=False))), icon='fa-music', template='blocks/songstreamblock.html', title='Song')),), blank=True, verbose_name='Songs'),
        ),
    ]
