# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-17 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_album_song_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumsongsrelationship',
            name='album_songs',
        ),
        migrations.DeleteModel(
            name='AlbumSongsRelationship',
        ),
    ]
