# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-17 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_auto_20160917_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genreclassalbumrelationship',
            old_name='genre',
            new_name='genres',
        ),
    ]
