# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('album', '0008_auto_20160917_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumindexpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='AlbumIndexPage',
        ),
    ]
