# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0009_auto_20160920_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['title'], 'verbose_name': 'Album', 'verbose_name_plural': 'Albums'},
        ),
        migrations.RenameField(
            model_name='album',
            old_name='album_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', help_text='The name of the page as it will appear in URLs e.g http://domain.com/blog/[my-slug]/', max_length=255),
            preserve_default=False,
        ),
    ]
