# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-22 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0010_auto_20160920_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumartistrelationship',
            old_name='ArtistRelationship',
            new_name='page',
        ),
        migrations.AlterField(
            model_name='albumartistrelationship',
            name='artist_name',
            field=models.ForeignKey(help_text='The artist(s) who made this album', on_delete=django.db.models.deletion.CASCADE, related_name='artist_album_relationship', to='artist.Artist'),
        ),
    ]
