# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-22 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0011_auto_20160922_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='song_details',
            field=wagtail.wagtailcore.fields.StreamField((('SongBlock', wagtail.wagtailcore.blocks.StructBlock((), icon='fa-music')),), blank=True, verbose_name='Songs'),
        ),
        migrations.AlterField(
            model_name='genreclassalbumrelationship',
            name='genres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_album_relationship', to='genre.GenreClass'),
        ),
        migrations.AlterField(
            model_name='subgenreclassalbumrelationship',
            name='subgenre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgenre_album_relationship', to='genre.SubgenreClass'),
        ),
    ]
