# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-22 16:56
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0013_auto_20160922_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='song_details',
            field=wagtail.wagtailcore.fields.StreamField((('Songs', wagtail.wagtailcore.blocks.StructBlock((('album_song_title', wagtail.wagtailcore.blocks.CharBlock(help_text='e.g. Waiting Room')), ('album_song_length', wagtail.wagtailcore.blocks.RegexBlock(error_messages={'invalid': 'Please format your entry nn:nn e.g. 03:10'}, help_text='e.g. 03:10', regex='^([0-9]){2}:([0-9]){2}$'))), icon='fa-music')),), blank=True, verbose_name='Songs'),
        ),
    ]
