# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-26 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Party on Wayne homepage'},
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='introduction',
            new_name='advert_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='image',
        ),
        migrations.AddField(
            model_name='homepage',
            name='advert_button',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_page_1',
            field=models.ForeignKey(blank=True, help_text='Choose the most important feature page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='First featured page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_page_2',
            field=models.ForeignKey(blank=True, help_text='Choose the second most important featured page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Second featured page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_page_3',
            field=models.ForeignKey(blank=True, help_text='Choose an important secondary page to feature.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Third featured page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_1',
            field=models.ForeignKey(blank=True, help_text='A featured section showing the four most recently published items from that section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Featured section one'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_2',
            field=models.ForeignKey(blank=True, help_text='A featured section showing the four most recently published items from that section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Featured section two'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_3',
            field=models.ForeignKey(blank=True, help_text='A featured section showing the four most recently published items from that section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Featured section three'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='site_description',
            field=wagtail.wagtailcore.fields.RichTextField(default='', help_text='A brief explanation of this page.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='site_description_title',
            field=models.CharField(default='', help_text='A title explaining this page.', max_length=255),
            preserve_default=False,
        ),
    ]
