# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-08 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20160627_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='advert_title',
            field=models.TextField(blank=True),
        ),
    ]
