# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-03 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_authorfeaturepagerelationship'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewRelatedPageRelationship',
            new_name='NewsRelatedPageRelationship',
        ),
        migrations.RenameField(
            model_name='newspage',
            old_name='news_image',
            new_name='image',
        ),
    ]
