# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-08 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standardpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='listing_introduction',
            field=models.TextField(blank=True, help_text="Text shown on listing pages, if empty will show 'Introduction' field content"),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='introduction',
            field=models.TextField(blank=True, help_text='Text to show at the top of the individual page'),
        ),
    ]
