# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-08 20:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('standardpage', '0002_auto_20160508_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 5, 8, 20, 52, 48, 632111, tzinfo=utc), verbose_name='Post date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='listing_introduction',
            field=models.CharField(blank=True, help_text="Text shown on listing pages, if empty will show 'Introduction' field content", max_length=250),
        ),
    ]
