# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-25 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenreClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(help_text='The genre. You can only have one e.g. metal', max_length=254, verbose_name='The genre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubgenreRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('subgenre', models.CharField(blank=True, max_length=255)),
                ('subgenre_in_editor', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgenre_relationship', to='genre.GenreClass')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
    ]
