# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-26 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenreClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(help_text='The genre. Something high level e.g. pop, metal, punk etc', max_length=254, verbose_name='The genre')),
                ('description', wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='A description of the genre')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='SubgenreClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgenre', models.CharField(blank=True, help_text="Be as esoteric as you'd like", max_length=255)),
                ('description', wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='A description of the sub-genre')),
            ],
            options={
                'verbose_name': 'Subgenre',
                'verbose_name_plural': 'Subgenres',
            },
        ),
        migrations.CreateModel(
            name='SubGenreRelationship',
            fields=[
                ('subgenreclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='genre.SubgenreClass')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('subgenre_in_editor', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_genre_relationship', to='genre.GenreClass')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
            bases=('genre.subgenreclass', models.Model),
        ),
    ]
