# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-08 23:16
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='sub_genre',
            field=wagtail.wagtailcore.fields.StreamField((('text', wagtail.wagtailcore.blocks.TextBlock('Sub-genre', icon='fa-music', label='Death metal, black metal etc.')),)),
        ),
    ]
