# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-26 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgenreclass',
            name='description',
            field=models.TextField(blank=True, help_text='A description of the sub-genre'),
        ),
        migrations.AlterField(
            model_name='subgenreclass',
            name='subgenre',
            field=models.CharField(help_text="Be as esoteric as you'd like", max_length=255),
        ),
    ]
