# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-25 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genreclass',
            options={'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
    ]
