# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-08 23:18
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0002_auto_20160509_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='sub_genre',
            field=wagtail.wagtailcore.fields.StreamField((('text', wagtail.wagtailcore.blocks.TextBlock(help_text='Death metal, black metal etc.', icon='fa-music', label='Sub-genre')),)),
        ),
    ]
