# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-26 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0002_auto_20160626_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='genre.GenreClass')),
                ('genre_in_editor', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_relationship', to='genre.SubgenreClass')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
