# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-26 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0003_genrerelationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genrerelationship',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='genrerelationship',
            name='genre_in_editor',
        ),
        migrations.DeleteModel(
            name='GenreRelationship',
        ),
    ]
