# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-08 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0003_auto_20160509_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(help_text='The parent genre e.g. metal', max_length=254, verbose_name='The genre'),
        ),
    ]
