# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-11 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0004_auto_20160626_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genreclass',
            options={'ordering': ['title'], 'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='subgenreclass',
            options={},
        ),
        migrations.RenameField(
            model_name='genreclass',
            old_name='description',
            new_name='genre_description',
        ),
        migrations.RenameField(
            model_name='genreclass',
            old_name='genre',
            new_name='title',
        ),
        migrations.AddField(
            model_name='genreclass',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', help_text='The name of the page as it will appear in URLs e.g http://domain.com/blog/[my-slug]/', max_length=255),
            preserve_default=False,
        ),
    ]
