# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-07 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0004_auto_20160626_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genreclass',
            name='description',
        ),
        migrations.AddField(
            model_name='genreclass',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', help_text='The name of the page as it will appear in URLs e.g http://domain.com/blog/[my-slug]/', max_length=255),
            preserve_default=False,
        ),
    ]
