# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-07 14:28
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0005_auto_20160907_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='genreclass',
            name='genre_description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='A description of the genre'),
        ),
    ]
