# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-07 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0006_genreclass_genre_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genreclass',
            old_name='genre',
            new_name='title',
        ),
    ]
