# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-23 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('genre', '0007_auto_20161023_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='genreclass',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Album cover image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
