# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-07 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0007_auto_20160907_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genreclass',
            options={'ordering': ['title'], 'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
    ]
