# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-07 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0008_auto_20160907_2208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenreClass',
            new_name='Genre',
        ),
    ]
