# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-12 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', help_text='The name of the page as it will appear in URLs e.g http://domain.com/blog/[my-slug]/', max_length=255),
            preserve_default=False,
        ),
    ]
