# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-08 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='biograpy',
            new_name='biography',
        ),
    ]
