# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-07 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20160912_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='job_title',
            field=models.CharField(blank=True, max_length=254, verbose_name="The author's title"),
        ),
    ]
