# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-08 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20160508_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='date',
        ),
        migrations.AddField(
            model_name='author',
            name='author_name',
            field=models.CharField(default=2, max_length=254, verbose_name="The author's name"),
            preserve_default=False,
        ),
    ]
