# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-08 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_auto_20160508_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_name',
            field=models.CharField(blank=True, max_length=254, verbose_name="The author's name"),
        ),
    ]
