# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-16 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_author_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='job_title',
            field=models.CharField(blank=True, help_text='e.g. punk rock person', max_length=254, verbose_name="The author's job title"),
        ),
    ]
